---
- hosts: ansible_nodes
  become: yes
  become_method: sudo

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes

    - name: Install packages
      become: true
      apt:
        name: "{{ packages }}"
      vars:
         packages:
            - apt-transport-https
            - ca-certificates
            - curl
            - software-properties-common
            - python3-pip
            - virtualenv
            - python3-setuptools
            - gnupg 
            - lsb-release
            - gccgo-go
            - net-tools

    - name: Add Docker GPG apt Key
      apt_key:
        url: 
          https://download.docker.com/linux/ubuntu/gpg
        state: 
          present

    - name: Add Docker Repository
      apt_repository:
        repo: 
          deb https://download.docker.com/linux/ubuntu bionic stable
        state: 
          present

    - name: Update apt and install docker-ce
      apt: 
        update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull default Docker image
      docker_image:
        name: caddy
        source: pull
    
    - name: Create containers caddy
      docker_container:
        name: "caddy"
        image: "caddy"
        command: "sudo docker run -d -p 3001:80 --name caddy -v /site:/srv/index.html -v caddy_data:/data -v caddy_config:/config caddy caddy file-server --browse"
        state: present
